### PR TITLE
Propagate linkValue and LinkType into edges

### PR DESCRIPTION
**Pull request by harisbal**
Hello Rick,
I was facing some issues with the transitions of some sankey-diagrams and realised that d.type was not propagated properly to edges. E.g.
https://github.com/ricklupton/d3-sankey-diagram/blob/26f924b9f99b32629deb79b951ea0f751b942786/src/diagram.js#L117-L121

`d.type` was not retrieved properly.
I think I've sorted out the issue but please have a look.
Cheers
-Haris

### CODE REVIEW

**Comment by ricklupton** [comment]
Hi Haris, thanks for picking this up!

Just to check I'm understanding that's going on properly, have you redefined `sankey().linkType()` to access the link type from another attribute instead of [the default `.type`](https://github.com/ricklupton/d3-sankey-diagram#layout-linkType)?

What I think happens currently -- which isn't necessarily right -- is that the sankey layout doesn't assign `.type` itself, but if your link objects already have a key called that then the link id string you linked to will work. But if you have customized `sankey.linkType()` then it will fail because `d.type` is undefined.

So I think probably your changes are right, and the layout should always set `link` and `value` just like it does `source` and `target` -- but this should be documented in the README to avoid confusion if you have custom `linkType` and `linkValue` accessors. Does that make sense?

If possible it would be great if you could:
1. Add a note to the [changelog](https://github.com/ricklupton/d3-sankey-diagram#changelog) that `link`, `value` and `id` are now set on link objects
2. Update the bit you quoted in d3-sankey-diagram to use `d.id` directly instead of calculating it again

**Comment by harisbal** [comment]
Hi Rick,
I thin you got this properly indeed. My issue occurred because I was using custom `linkType` accessor and therefore `link.type` and was not getting updated.

I'm happy to add a note to the changelog but I'm not sure though what you mean about the README part. Why always assigning the `type `and `value`  would cause any confusion.

BTW, I just realised that `edge.data.id = `${e.v}-${e.w}-${e.name}`` is not actually required so I will comment out again.

Cheers

**Comment by ricklupton** [comment]
> I'm happy to add a note to the changelog

Thanks.

> I'm not sure though what you mean about the README part. Why always assigning the `type `and `value` would cause any confusion.

I just meant it should be added to the list of attributes that are set by the layout -- along with `source`, `target` etc. But looking again this isn't actually documented anywhere in the README! So don't worry.

**Comment by harisbal** [comment]
Let me know if that's alright and thank you very much for this awesome library!
By the way, have you considered of asking d3-sankey developers to merge your library?
I know this is not the place to have this discussion but I was really keen to ask.
Cheers
-Haris

**Comment by ricklupton** [comment]
Thanks! That's great.

I'm open to merging these d3-sankey[-diagram] libraries, but I've not discussed it so far. It'd take a bit of work to integrate the different layout algorithms, as d3-sankey-diagram and d3-sankey make different choices about how to position nodes. Both have benefits in different diagrams.

**Comment by harisbal** [comment]
I see. In any case thank you very much, I'll keep suggesting improvements as I'm using the library!

**Pull request merged**
